# Site settings
title: David Roberts
email: dwmroberts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

instagram_username: artbydavidroberts
facebook_username: ArtByDavidRoberts

# Build settings
markdown: kramdown
